FROM node:20-alpine AS development

WORKDIR /app

ENV NODE_ENV=development

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/notifications-service ./apps/notifications-service

RUN pnpm install

WORKDIR /app/apps/notifications-service

EXPOSE 3004

CMD ["pnpm", "dev"]
