FROM node:20-alpine AS development

WORKDIR /app

ENV NODE_ENV=development

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/auth-service ./apps/auth-service

RUN pnpm install

WORKDIR /app/apps/auth-service

EXPOSE 3002

CMD ["pnpm", "dev"]
