FROM node:20-alpine AS development

WORKDIR /app

ENV NODE_ENV=development

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/tasks-service ./apps/tasks-service

RUN pnpm install

WORKDIR /app/apps/tasks-service

EXPOSE 3003

CMD ["pnpm", "dev"]
