FROM node:20-alpine AS development

WORKDIR /app

ENV NODE_ENV=development

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages ./packages
COPY apps/api-gateway ./apps/api-gateway

RUN pnpm install

WORKDIR /app/apps/api-gateway

EXPOSE 3001

CMD ["pnpm", "dev"]
